name: CI

on:
  pull_request:
    branches: [master]

jobs:
  lint_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        #   Clean instal for Ci server
      - run: npm ci
      - run: npm run lint
      # - run: npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run build --prod
